/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-03-20 15:12:36 UTC)
 * on 2013-03-27 at 12:37:25 UTC 
 * Modify at your own risk.
 */

package com.battlelancer.seriesguide.beta.showendpoint;

/**
 * Service definition for Showendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ShowendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Showendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(com.google.api.client.googleapis.GoogleUtils.VERSION.equals("1.14.1-beta"),
        "You are currently running with version %s of google-api-client. " +
        "You need version 1.14.1-beta of google-api-client to run version " +
        "1.14.1-beta of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://1.myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "showendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Showendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Showendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getShow".
   *
   * This request holds the parameters needed by the the showendpoint server.  After setting any
   * optional parameters, call the {@link GetShow#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetShow getShow(java.lang.String id) throws java.io.IOException {
    GetShow result = new GetShow(id);
    initialize(result);
    return result;
  }

  public class GetShow extends ShowendpointRequest<com.battlelancer.seriesguide.beta.showendpoint.model.Show> {

    private static final String REST_PATH = "show/{id}";

    /**
     * Create a request for the method "getShow".
     *
     * This request holds the parameters needed by the the showendpoint server.  After setting any
     * optional parameters, call the {@link GetShow#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetShow#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetShow(java.lang.String id) {
      super(Showendpoint.this, "GET", REST_PATH, null, com.battlelancer.seriesguide.beta.showendpoint.model.Show.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetShow setAlt(java.lang.String alt) {
      return (GetShow) super.setAlt(alt);
    }

    @Override
    public GetShow setFields(java.lang.String fields) {
      return (GetShow) super.setFields(fields);
    }

    @Override
    public GetShow setKey(java.lang.String key) {
      return (GetShow) super.setKey(key);
    }

    @Override
    public GetShow setOauthToken(java.lang.String oauthToken) {
      return (GetShow) super.setOauthToken(oauthToken);
    }

    @Override
    public GetShow setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetShow) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetShow setQuotaUser(java.lang.String quotaUser) {
      return (GetShow) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetShow setUserIp(java.lang.String userIp) {
      return (GetShow) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetShow setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetShow set(String parameterName, Object value) {
      return (GetShow) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertShow".
   *
   * This request holds the parameters needed by the the showendpoint server.  After setting any
   * optional parameters, call the {@link InsertShow#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.battlelancer.seriesguide.beta.showendpoint.model.Show}
   * @return the request
   */
  public InsertShow insertShow(com.battlelancer.seriesguide.beta.showendpoint.model.Show content) throws java.io.IOException {
    InsertShow result = new InsertShow(content);
    initialize(result);
    return result;
  }

  public class InsertShow extends ShowendpointRequest<com.battlelancer.seriesguide.beta.showendpoint.model.Show> {

    private static final String REST_PATH = "show";

    /**
     * Create a request for the method "insertShow".
     *
     * This request holds the parameters needed by the the showendpoint server.  After setting any
     * optional parameters, call the {@link InsertShow#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertShow#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.battlelancer.seriesguide.beta.showendpoint.model.Show}
     * @since 1.13
     */
    protected InsertShow(com.battlelancer.seriesguide.beta.showendpoint.model.Show content) {
      super(Showendpoint.this, "POST", REST_PATH, content, com.battlelancer.seriesguide.beta.showendpoint.model.Show.class);
    }

    @Override
    public InsertShow setAlt(java.lang.String alt) {
      return (InsertShow) super.setAlt(alt);
    }

    @Override
    public InsertShow setFields(java.lang.String fields) {
      return (InsertShow) super.setFields(fields);
    }

    @Override
    public InsertShow setKey(java.lang.String key) {
      return (InsertShow) super.setKey(key);
    }

    @Override
    public InsertShow setOauthToken(java.lang.String oauthToken) {
      return (InsertShow) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertShow setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertShow) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertShow setQuotaUser(java.lang.String quotaUser) {
      return (InsertShow) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertShow setUserIp(java.lang.String userIp) {
      return (InsertShow) super.setUserIp(userIp);
    }

    @Override
    public InsertShow set(String parameterName, Object value) {
      return (InsertShow) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listShow".
   *
   * This request holds the parameters needed by the the showendpoint server.  After setting any
   * optional parameters, call the {@link ListShow#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListShow listShow() throws java.io.IOException {
    ListShow result = new ListShow();
    initialize(result);
    return result;
  }

  public class ListShow extends ShowendpointRequest<com.battlelancer.seriesguide.beta.showendpoint.model.CollectionResponseShow> {

    private static final String REST_PATH = "show";

    /**
     * Create a request for the method "listShow".
     *
     * This request holds the parameters needed by the the showendpoint server.  After setting any
     * optional parameters, call the {@link ListShow#execute()} method to invoke the remote operation.
     * <p> {@link
     * ListShow#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListShow() {
      super(Showendpoint.this, "GET", REST_PATH, null, com.battlelancer.seriesguide.beta.showendpoint.model.CollectionResponseShow.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListShow setAlt(java.lang.String alt) {
      return (ListShow) super.setAlt(alt);
    }

    @Override
    public ListShow setFields(java.lang.String fields) {
      return (ListShow) super.setFields(fields);
    }

    @Override
    public ListShow setKey(java.lang.String key) {
      return (ListShow) super.setKey(key);
    }

    @Override
    public ListShow setOauthToken(java.lang.String oauthToken) {
      return (ListShow) super.setOauthToken(oauthToken);
    }

    @Override
    public ListShow setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListShow) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListShow setQuotaUser(java.lang.String quotaUser) {
      return (ListShow) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListShow setUserIp(java.lang.String userIp) {
      return (ListShow) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListShow setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListShow setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListShow set(String parameterName, Object value) {
      return (ListShow) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeShow".
   *
   * This request holds the parameters needed by the the showendpoint server.  After setting any
   * optional parameters, call the {@link RemoveShow#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveShow removeShow(java.lang.String id) throws java.io.IOException {
    RemoveShow result = new RemoveShow(id);
    initialize(result);
    return result;
  }

  public class RemoveShow extends ShowendpointRequest<com.battlelancer.seriesguide.beta.showendpoint.model.Show> {

    private static final String REST_PATH = "show/{id}";

    /**
     * Create a request for the method "removeShow".
     *
     * This request holds the parameters needed by the the showendpoint server.  After setting any
     * optional parameters, call the {@link RemoveShow#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveShow#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveShow(java.lang.String id) {
      super(Showendpoint.this, "DELETE", REST_PATH, null, com.battlelancer.seriesguide.beta.showendpoint.model.Show.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveShow setAlt(java.lang.String alt) {
      return (RemoveShow) super.setAlt(alt);
    }

    @Override
    public RemoveShow setFields(java.lang.String fields) {
      return (RemoveShow) super.setFields(fields);
    }

    @Override
    public RemoveShow setKey(java.lang.String key) {
      return (RemoveShow) super.setKey(key);
    }

    @Override
    public RemoveShow setOauthToken(java.lang.String oauthToken) {
      return (RemoveShow) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveShow setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveShow) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveShow setQuotaUser(java.lang.String quotaUser) {
      return (RemoveShow) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveShow setUserIp(java.lang.String userIp) {
      return (RemoveShow) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveShow setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveShow set(String parameterName, Object value) {
      return (RemoveShow) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateShow".
   *
   * This request holds the parameters needed by the the showendpoint server.  After setting any
   * optional parameters, call the {@link UpdateShow#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.battlelancer.seriesguide.beta.showendpoint.model.Show}
   * @return the request
   */
  public UpdateShow updateShow(com.battlelancer.seriesguide.beta.showendpoint.model.Show content) throws java.io.IOException {
    UpdateShow result = new UpdateShow(content);
    initialize(result);
    return result;
  }

  public class UpdateShow extends ShowendpointRequest<com.battlelancer.seriesguide.beta.showendpoint.model.Show> {

    private static final String REST_PATH = "show";

    /**
     * Create a request for the method "updateShow".
     *
     * This request holds the parameters needed by the the showendpoint server.  After setting any
     * optional parameters, call the {@link UpdateShow#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateShow#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.battlelancer.seriesguide.beta.showendpoint.model.Show}
     * @since 1.13
     */
    protected UpdateShow(com.battlelancer.seriesguide.beta.showendpoint.model.Show content) {
      super(Showendpoint.this, "PUT", REST_PATH, content, com.battlelancer.seriesguide.beta.showendpoint.model.Show.class);
    }

    @Override
    public UpdateShow setAlt(java.lang.String alt) {
      return (UpdateShow) super.setAlt(alt);
    }

    @Override
    public UpdateShow setFields(java.lang.String fields) {
      return (UpdateShow) super.setFields(fields);
    }

    @Override
    public UpdateShow setKey(java.lang.String key) {
      return (UpdateShow) super.setKey(key);
    }

    @Override
    public UpdateShow setOauthToken(java.lang.String oauthToken) {
      return (UpdateShow) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateShow setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateShow) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateShow setQuotaUser(java.lang.String quotaUser) {
      return (UpdateShow) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateShow setUserIp(java.lang.String userIp) {
      return (UpdateShow) super.setUserIp(userIp);
    }

    @Override
    public UpdateShow set(String parameterName, Object value) {
      return (UpdateShow) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Showendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Showendpoint}. */
    @Override
    public Showendpoint build() {
      return new Showendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ShowendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setShowendpointRequestInitializer(
        ShowendpointRequestInitializer showendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(showendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
