/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-03-20 15:12:36 UTC)
 * on 2013-03-28 at 19:41:35 UTC 
 * Modify at your own risk.
 */

package com.uwetrottmann.seriesguide.showendpoint.model;

/**
 * Model definition for Show.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Show extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean favorite;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String getGlueId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean hidden;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean syncEnabled;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getFavorite() {
    return favorite;
  }

  /**
   * @param favorite favorite or {@code null} for none
   */
  public Show setFavorite(java.lang.Boolean favorite) {
    this.favorite = favorite;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGetGlueId() {
    return getGlueId;
  }

  /**
   * @param getGlueId getGlueId or {@code null} for none
   */
  public Show setGetGlueId(java.lang.String getGlueId) {
    this.getGlueId = getGlueId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getHidden() {
    return hidden;
  }

  /**
   * @param hidden hidden or {@code null} for none
   */
  public Show setHidden(java.lang.Boolean hidden) {
    this.hidden = hidden;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Show setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getSyncEnabled() {
    return syncEnabled;
  }

  /**
   * @param syncEnabled syncEnabled or {@code null} for none
   */
  public Show setSyncEnabled(java.lang.Boolean syncEnabled) {
    this.syncEnabled = syncEnabled;
    return this;
  }

  @Override
  public Show set(String fieldName, Object value) {
    return (Show) super.set(fieldName, value);
  }

  @Override
  public Show clone() {
    return (Show) super.clone();
  }

}
